# Generated by Django 6.0.6 on 2026-06-13 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Эмейл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('description', models.TextField(verbose_name='Описание')),
                ('mark', models.CharField(blank=True, max_length=100, null=True, verbose_name='Клеймо')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата находки')),
                ('status', models.CharField(choices=[('active', 'Ищет хозяина'), ('found', 'Хозяин найден'), ('on_moderation', 'На модерации')], default='on_moderation', max_length=30, verbose_name='Статус')),
                ('photos', models.JSONField(default=list, verbose_name='Список путей к фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pets.district', verbose_name='Район')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pets.kind', verbose_name='Вид животного')),
            ],
        ),
    ]
