# Generated by Django 6.0.6 on 2026-06-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_order_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mark',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Особая примета'),
        ),
    ]
